server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  profiles:
    active: local # 默认激活本地环境，上线时改为 prod
  application:
    name: mcp-client
  datasource:
    url: jdbc:mysql://120.26.30.114:3306/ai_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wangbing201708
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      port: 6379
      host: 120.26.30.114
      password: wangbing201708

  ai:
    dashscope:
      api-key: sk-4246e826d02342b4bb713f68a1ff7b6f
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
    mcp:
      client:
        type: async
        request-timeout: 60s
        toolcallback:
          enabled: true
        #        stdio:
        #          servers-configuration: classpath:/mcp-server-mac.json5    使用不同开发环境的yml配置文件
        # sse:
        #   connections:
        #     mcp-server1:
        #       url: http://localhost:8014
mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.vanpine.mcpclient: DEBUG




