server:
  port: 8080
  servlet:
    encoding:
      enabled: true
      force: true
      charset: utf-8
spring:
  application:
    name: mcp-client
  data:
    redis:
      port: 6380
      host: 120.26.30.114
      password: wangbing201708

  ai:
    dashscope:
      api-key: sk-4246e826d02342b4bb713f68a1ff7b6f
      embedding:
        options:
          model: text-embedding-v3
    vectorstore:
      redis:
        initialize-schema: true
        index-name: custom-index
        prefix: custom-prefix
    mcp:
      client:
        type: async
        request-timeout: 60s
        toolcallback:
          enabled: true
        stdio:
          servers-configuration: classpath:/mcp-server.json5
        # sse:
        #   connections:
        #     mcp-server1:
        #       url: http://localhost:8014
logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.vanpine.mcpclient: DEBUG




